// 导出所有 API
export { authApi } from './auth'
export { userApi } from './user'
export { adminUserApi } from './adminUser'
export { adminModelConfigApi } from './adminModelConfig'
export { adminModelProviderApi } from './adminModelProvider'
export { adminMcpConfigApi, adminMcpToolApi } from './adminMcpConfig'
export { adminMcpInstanceApi } from './adminMcpInstance'
export { adminSkillConfigApi } from './adminSkillConfig'
export { adminSkillHubApi } from './adminSkillHub'
export { adminSkillFileApi, type FileNode } from './adminSkillFile'
export { deptApi } from './dept'
export { menuApi } from './menu'
export { desktopIconApi } from './desktopIcon'
export { availableResourceApi } from './availableResource'
export { chatApi } from './chat'
export { memoryApi } from './memory'
export { userModelConfigApi } from './userModelConfig'

// 导出类型
export type { LoginRequest, LoginResponse, CurrentUserResponse, ChangePasswordRequest } from './auth'
export type { UserInfo, RoleInfo, CreateUserRequest, UpdateUserRequest, ResetPasswordRequest } from './user'
export type { UserInfo as AdminUserInfo, RoleInfo as AdminRoleInfo, CreateUserRequest as AdminCreateUserRequest, UpdateUserRequest as AdminUpdateUserRequest, AssignUserRoleRequest, RemoveUserRoleRequest, ResetPasswordRequest as AdminResetPasswordRequest } from './adminUser'
export type { ModelConfigInfo, ModelConfigWithOwner, CreateModelConfigRequest, UpdateModelConfigRequest } from './adminModelConfig'
export type { ModelProviderInfo, CreateModelProviderRequest, UpdateModelProviderRequest } from './adminModelProvider'
export type { McpConfigInfo, McpToolInfo, CreateMcpConfigRequest, UpdateMcpConfigRequest, CreateMcpToolRequest, UpdateMcpToolRequest, CreateMcpToolGrantRequest } from './adminMcpConfig'
export type { McpInstanceInfo } from './adminMcpInstance'
export type { SkillConfigInfo, CreateSkillConfigRequest, UpdateSkillConfigRequest } from './adminSkillConfig'
export type { HubSearchResult } from './adminSkillHub'
export type { DeptInfo, CreateDeptRequest, UpdateDeptRequest } from './dept'
export type { MenuInfo } from './menu'
export type { DesktopIconInfo, CreateDesktopIconRequest, UpdateDesktopIconRequest } from './desktopIcon'
